### ISSUE TITLE
Gap in the top header

### ISSUE THREAD

**Issue by linuxhw** [SychO9/smf-potato-theme#49]
There is a gap in the top header on the 15-inch screen. See pic:

![Potato-0](https://user-images.githubusercontent.com/15686469/145949202-ba8e683c-7484-47b9-92c1-21e90cb185b4.png)

No gap on the 14-inch screen if Firefox is in the full-screen mode. But it appears if you reduce the width of the window.

Please help to workaround this.

**Comment by SychO9** [comment]
The theme isn't really fit for such large logo images (more than 60px height), I guess I should mention that in the theme settings. or enforce it with CSS, or both.

**Comment by linuxhw** [comment]
Reducing of the image size to 60px doesn't solve the issue:
![Potato-1](https://user-images.githubusercontent.com/15686469/146507010-e7872015-a83a-45a1-97c3-9f64712bf29f.png)

**Comment by linuxhw** [comment]
Is it possible to somehow fill this rectangle?

**Comment by SychO9** [comment]
Oh actually, this is a better solution:

```css
.top-section::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 60px;
  background: var(--top-section-background);
  z-index: -1;
}
```
